-- SQLite

-- Users
CREATE TABLE IF NOT EXISTS "users"
(
    id VARCHAR(45) PRIMARY KEY NOT NULL,
    email VARCHAR(160)  NOT NULL,
    password VARCHAR(160)  NOT NULL,
    name VARCHAR(160)  NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Messages
CREATE TABLE IF NOT EXISTS "messages"
(
    id VARCHAR(45) PRIMARY KEY NOT NULL,
    message TEXT NOT NULL,
    type VARCHAR(45),
    user_id VARCHAR(160)  NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) 
      REFERENCES users (id) 
         ON DELETE CASCADE 
         ON UPDATE NO ACTION
);

